### ISSUE TITLE
how to add websocket when deploying by WAR file

### ISSUE THREAD

**Issue by ludicrousdisplay** [ringo/ringojs#400] opened 2018-09-12 22:58 UTC
I am hoping to figure out how to setup websockets when deploying a ringo webapp as a war file. 

The two examples that show how to add a callback function to the websocket are using httpserver like this...

```
    var server = require("ringo/httpserver").main(module.id);
    server.getDefaultContext().addWebSocket("/websocket", onconnect);
```

However I can't get this to work when deploying as a war file on Glassfish because a TypeError gets thrown when trying to get the httpserver. 

`    var server = require("ringo/httpserver").main(module.id);
`

Specifically, using ringojs v1.2.1 with Glassfish 4.1.1 the error is:

```
Severe:   TypeError: [JavaPackage org.eclipse.jetty.server.Server] is not a function, it is object.
Severe:   at ringo/httpserver.js:492 (Server)
	at ringo/httpserver.js:635 (init)
	at ringo/httpserver.js:720 (main)
	at main.js:27
	at ringo/jsgi/connector.js:34 (handleRequest)
```

Is there another object to which I can attach the websocket onconnect function? Any pointers to documentation or source code that I should read up on will be appreciated.

Thanks :)

**Comment by ludicrousdisplay** [comment] 2018-09-20 03:55
Thanks, the Jetty classes were indeed missing from the war file, so I've included all of the JAR files under lib/ivy and I am no longer getting the TypeError :) 

Unfortunately I am now getting an error when trying to get a reference to the httpserver with the following line of code...

   var server = require("ringo/httpserver").main(module.id);

I expect this error is born out of my lack of understanding on what is going on behind the scenes. On linux I get a bind error that the address is already in use, which isn't entirely surprising. 

As always, any insight is appreciated!

**Comment by ludicrousdisplay** [comment] 2018-09-21 01:18
Thanks, the webapp skeleton works well for me as long as I don't try to use httpserver in order to set up the websocket. If you know of a way to connect the websocket via Ringo to the JSGI servlet (instead of httpserver) I can try that out. No worries if not, I have another approach I am working on but will have time to revisit this in January if anyone else is interested. 

Thanks again!

**Comment by botic** [comment] 2018-09-26 07:08
I'll close this issue for now, since it's not a bug.

**Closed by botic** 2018-09-26 07:08 UTC
Labels: awaiting reply, java
