### ISSUE TITLE
Unable to clone the Exchange.headers object

### ISSUE THREAD

**Issue by ndufrane** [ringo/ringojs#287] opened 2015-02-18 13:23 UTC
Hi,

When tring to iterate over the attibutes of the exchange.headers objet i got NullPointerException error.
This seems to be caused by a null attribute in the headers.

The exchange.headers objet :
`{null=[HTTP/1.1 200 OK], Date=[Wed, 18 Feb 2015 13:00:45 GMT], Transfer-Encoding=[chunked], Content-Encoding=[gzip], Last-Modified=[Wed, 18 Feb 2015 09:57:23 GMT], Content-Type=[application/xml;charset=UTF-8], Server=[Apache-Coyote/1.1]} `

The code causing a null pointer exception:
* var header = new Headers(exchange.header)
* or simply : objects.clone(exchange.header)

**Comment by botic** [comment] 2015-02-18 19:05
The problem is the `null` key in the headers object. This leads to a NullPointerException. See #288

**Comment by botic** [comment] 2015-02-19 08:13
Fixed in master: https://github.com/ringo/ringojs/pull/288/files

**Closed by botic** 2015-02-19 08:13 UTC
Labels: javascript

**Comment by ndufrane** [comment] 2015-02-19 13:18
Thanks !
