### ISSUE TITLE
Possible file leak on require function?

### ISSUE THREAD

**Issue by spamcampus** [ringo/ringojs#332] opened 2016-04-04 00:15 UTC
Hello?

I made an stick based web app.
For the live deployment, I used jetty runner on ubuntu

when i launched stick app war file into jetty runner, it is ok for a while.

However, some times later, the app throws too much file error from static.js
or throws stream closed error on wherever require function locates.

so i checked following
ls -l /proc/PID/fd

and i found that there were many files but i can see those files are found on the list over and over again multiple times and it reached 4096 files
they all *.js files there's none of static one.

i am not a ringojs expert,
but if you're the expert, would you like to check out the possibility of file leak on require function?

thank you.

**Comment by grob** [comment] 2016-04-04 17:57
i can't confirm this: we have several ringojs apps running for months under (partially heavy) load without any issues, although they are not deployed as .war file. i just checked to be sure, and one of these apps has no open .js file descriptors at all. so i suspect there's something else going wrong here, but it's hard to guess from the information you posted.

**Comment by botic** [comment] 2016-04-04 21:52
If there is a bug, it might hide in the repository management. If you are deploying a WAR a different code repository type is used at startup. Are you using Ringo with the `production` switch?

**Comment by spamcampus** [comment] 2016-04-05 03:08
@grob 
Thanks for checking this out.
wow your file descriptor status with "ls -l /proc/PID/fd" are not contains any .js files?
i am using war file for the just deploy simplicity (embedding ringojs for not installing for the server) and enabling https easily (somehow i can not enable https with ringo command - jetty runner seems quite simple)


@botic 
No. i am not using production switch yet.

the only thing i have changed from default web.xml
is async-supported = true

strange things though,
i've test my app with http://file-leak-detector.kohsuke.org/
and i found that file descriptor is seems not increasing.
it is very steady under 60.
but i don't know why "ls -l /proc/PID/fd/" shows different results.

Maybe, i should try production=true setting and see how it turns out.

By the way, Ringojs is fun to use, no more callback spagetti with JAVA ecostream Yay!

**Comment by sclee15** [comment] 2016-04-15 04:23
@botic I am sorry to inform you that the problem is still exist even the Production flag True in the web.xml

I can see many duplicate File descriptors on many js files

for example,
/webapp/WEB-INF/packages/reinhardt/lib/tag/logic.js
this file has 24 duplicates

thank you.

**Comment by sclee15** [comment] 2016-04-15 04:44
this is possibly related?
https://groups.google.com/forum/#!topic/ringojs/_-uUTWkDMQI

**Comment by grob** [comment] 2016-04-15 08:29
Maybe the problem isn't `require()` but a module utilizing it?:
- Was your webapp in production (i.e. answering requests) when you checked the open files?
- Can you check if the majority of the open file descriptors you're seeing are pointing to files in a specific package?

**Comment by sclee15** [comment] 2016-04-16 01:25
I think i figured out what causes this issue.

you can refer this pull request
https://github.com/ringo/ringojs/pull/333

@grob thank you for replying. Yes. it was in production = true in web.xml. most file descriptors are shown in random manner. However, the issue is fixed after i modified the moduleLoader.

Thank you all.

**Comment by botic** [comment] 2016-04-20 09:42
Fixed in #333

**Closed by botic** 2016-04-20 09:42 UTC
